Update worker.js
InkoHX/vm2-discordjs pull request #32
Opened 2021-09-12 07:07 UTC by kage-sakura

vm2.VMから返却されたSet, Map, Date,  WeakSet, WeakMap, ArrayBuffer, TypedArray, BoxedPrimitiveなどをutil.inspectすると、情報が抜け落ちる問題の修正

2021-09-12 07:28 UTC, InkoHX commented
@kage-sakura `npm run format`を使用してコードを整えてください🙏

2021-09-12 07:52 UTC, kage-sakura commented
了解しました

2021-09-12 08:27 UTC, InkoHX commented on src/worker.js
> +  const result = await vm.run(code)
`await`使用してますけど、これはどういった理由でしょうか？

2021-09-12 09:44 UTC, kage-sakura commented on src/worker.js
> +  const result = await vm.run(code)
「JSONによるSerializationで結果が異なる問題を修正」より前は、
(意図していなかったのかもしれませんが、)
Promiseを返すコードを実行したとき、Promiseを解決した値が表示されていたので、
それに合わせるために、await を使用しました。

例)
[コード] `(async () => 67)()`
[結果] `67`

2021-09-12 10:38 UTC, InkoHX commented on src/worker.js
> +  const result = await vm.run(code)
Thenableなオブジェクトを`await`するケースがあるとユーザーが想定した結果と異なる場合が発生しそうなので、返り値がPromiseである場合のみ`await`を使用するように処理を変更したほうがいいと思います。

2021-09-12 10:45 UTC, InkoHX commented on src/worker.js
> +  const result = await vm.run(code)
最終的に値を`await`することをユーザーが知らない限り、やめたほうがいいです。

2021-09-12 13:04 UTC, kage-sakura commented
・Promise以外のThenableオブジェクトをawaitしないようにしました。
・VM内で RegExp, Number, String... に対して代入が行われても大丈夫なように、ソースコードを実行する前に、それらを取得するように変更しました。

2021-09-12 16:17 UTC, InkoHX commented on src/worker.js
> +    result = (await promiseProtoThen.call(result, a => [a]))[0]
```suggestion
    result = (await promiseProtoThen.call(result, value => value, reason => reason))
```

このように変更すると、`reject`された場合の値も送信することができました。

![image](https://user-images.githubusercontent.com/33122816/132994681-134d0719-97e8-4554-8853-d3a03094dd19.png)

ただ、余計なスタックトレースが表示されてて最悪になってしまった...

2021-09-12 16:23 UTC, InkoHX commented
@kage-sakura お疲れ様です。

提案なんですけど、一つのPRに２つ以上の変更を取り込むとどんどんマージしづらくなってくるので、このPRで目的の「コレクションのデータ構造明らかにする」と「Promiseの値を取り出す」は別件としてPRを立ててみませんか？

2021-09-13 01:56 UTC, kage-sakura commented
確かに別件で立てた方がわかりやすいですし、やりやすいですね。
そうします。

2021-09-13 06:49 UTC, InkoHX requested changes

2021-09-13 06:49 UTC, InkoHX commented on src/worker.js
> +  let result = vm.run(code)
```suggestion
  const result = vm.run(code)
```

2021-09-13 13:25 UTC, InkoHX approved these changes

2021-09-13 13:28 UTC, InkoHX commented
私が見た限り大丈夫そうなので、CI通ったらマージさせていただきます！

2021-09-14 13:25 UTC, merged

2021-09-14 13:25 UTC, InkoHX commented
ありがとうございました！