Update to discord.js v13.6.0
InkoHX/vm2-discordjs pull request #49
Opened 2022-02-02 05:00 UTC by Dirain1700

usage: [Dirain1700/rankbot at dev](https://github.com/Dirain1700/rankbot/blob/dev/main.js#L38-L72)

まだ2000文字以上の結果を出力するテストが出来てないので下書きで失礼します…

2022-02-03 06:16 UTC, Dirain1700 commented
修正が完了しました。
なお、`npm run format`の後に`npx eslint --fix src/*`でsemicolon等の修正をしています。
eslintのconfigファイルは[.eslintrc.json](https://github.com/Dirain1700/rankbot/blob/dev/.eslintrc.json)を使用しています。
なお、この後package.jsonのenginesを16.9.0に修正します。

2022-02-03 07:05 UTC, InkoHX commented
@Dirain1700  このリポジトリの環境ではESLintを使用しておらず、`.eslintrc`も書いていません
個人で静的解析をかけるのは良いと思いますが、コードスタイルは`.prettierrc.toml`の元ESLintと統合が起きないように`eslint-config-prettier`を使用してください。

2022-02-03 07:32 UTC, InkoHX requested changes
すみません
後でコードじっくり読みます。

2022-02-03 07:32 UTC, InkoHX commented on src/index.js
> +    );
Discord.jsの[ソースコード](https://github.com/discordjs/discord.js/blob/stable/src/structures/MessageAttachment.js#L8)を見ると、これでも確かに動作するのですが[ドキュメント](https://discord.js.org/#/docs/discord.js/stable/class/MessageAttachment)にはコンストラクタに渡す最初の値がOptionalではないというのと、なぜファイル名を`result.js`にされたのか分かりませんがJavaScriptのコードを出力するものではないので`result.txt`で問題ないと考えています。

以上の２つで、ここは下記のコードで大丈夫です。

```suggestion
    const file = new MessageAttachment(Buffer.from(content), 'result.txt')
```

2022-02-03 07:59 UTC, Dirain1700 commented
変数の名前の件、了解しました。
ただし、`codeBlock`に関しては、[@discordjs/buildersの関数](https://discordjs.guide/popular-topics/builders.html#code-blocks)のため(可能ですが)CamelCaseにするべきでないと考えますが、どうでしょうか?

2022-02-03 09:15 UTC, InkoHX commented
> 変数の名前の件、了解しました。 ただし、`codeBlock`に関しては、[@discordjs/buildersの関数](https://discordjs.guide/popular-topics/builders.html#code-blocks)のため(可能ですが)CamelCaseにするべきでないと考えますが、どうでしょうか?

`codeBlock`は`camelCase`です。

2022-02-03 10:37 UTC, InkoHX requested changes
全て確認しました。

2022-02-03 10:37 UTC, InkoHX commented on src/structures/message.js
> +        errors: ['time'],
```suggestion
        max: 1,
        idle: 60000,
        errors: ['idle'],
```

2022-02-03 10:37 UTC, InkoHX commented on src/structures/message.js
> +        errors: ['time'],
```suggestion
        max: 1,
        idle: 60000,
        errors: ['idle'],
```

2022-02-03 10:37 UTC, InkoHX commented on src/index.js
>    },
```suggestion
```

2022-02-03 10:37 UTC, InkoHX commented on src/index.js
>    ws: {
```suggestion
```

2022-02-03 10:37 UTC, InkoHX commented on src/structures/message.js
> +module.exports = Message
`Message`クラスをインポートして使うわけではないので、`module.exports`は不要です。
```suggestion
```

2022-02-03 10:37 UTC, InkoHX commented on src/structures/message.js
> +  run().catch(console.error)
```suggestion
  reply.react(wastebasket)
    .then(() => run())
    .catch(console.error)
```

2022-02-03 10:37 UTC, InkoHX commented on src/structures/message.js
> +  await reply.react(wastebasket)
```suggestion
```

2022-02-03 10:37 UTC, InkoHX commented on package.json
> +    "node": ">=16.9.0"
Discord.jsが必要とするバージョンは`v16.6.0`以上なので、最初に修正して頂いたバージョンで問題ありません。
```suggestion
    "node": ">=16.6.0"
```

2022-02-03 11:20 UTC, Dirain1700 commented on src/structures/message.js
> +        errors: ['time'],
1にすると自分(bot)のリアクションに反応してしまうため、2にしています。

2022-02-03 12:27 UTC, Dirain1700 commented
修正が完了しました。structuresフォルダはstructuresを使用していないので消して中身だけ移動させてもいいですが、お任せします。

2022-02-03 12:30 UTC, InkoHX requested changes

2022-02-03 12:30 UTC, InkoHX commented on src/index.js
>  const codeBlockRegex = /^`{3}(?<lang>[a-z]+)\n(?<code>[\s\S]+)\n`{3}$/mu
```suggestion
const codeBlockRegex = /^`{3}(?<language>[a-z]+)\n(?<code>[\s\S]+)\n`{3}$/mu
```

2022-02-03 12:31 UTC, InkoHX commented
> 修正が完了しました。structuresフォルダはstructuresを使用していないので消して中身だけ移動させてもいいですが、お任せします。

やっていることは、v12のStructuresと変わらないのでそのままでいいです。

2022-02-03 14:16 UTC, InkoHX approved these changes

2022-02-03 23:50 UTC, Dirain1700 commented
Node.js CIが落ちた理由、`npm ci`がインストールできていないからだと思われますが、installに変更しませんか?

2022-02-04 00:01 UTC, InkoHX commented
フォーマッタがNG出してるだけなので、`npm run format`お願いします。
![image](https://user-images.githubusercontent.com/33122816/152449498-87b880b0-2cda-4647-a563-855f131c9d49.png)

2022-02-04 01:16 UTC, Dirain1700 commented
> フォーマッタがNG出してるだけなので、`npm run format`お願いします。
> ![image](https://user-images.githubusercontent.com/33122816/152449498-87b880b0-2cda-4647-a563-855f131c9d49.png)

それは失礼しました。

2022-02-04 01:44 UTC, merged

2022-02-04 01:45 UTC, InkoHX commented
PRありがとうございました！